
Point playerSize = player.GetSize ();
Point screenSize = GetWindowSize ();

void Start ()
{

}

void BeforeEnterScene ()
{
	AddOnEnterCallback ("CITY_EXIT", OnCityExitEnter);

	camera.SetFollowActor (GetActor ("PLAYER"));
}

void AfterLeaveScene ()
{
}

void OnCityExitEnter (Point p)
{
//	Color color = COLOR_BLACK;
//	SceneFadeInOut (400, 400, color);
	SetActiveScene ("0_home/0_0_home.scn", false);
}

void Update (float deltaTime)
{
}
