#include "../../Data/scripts/Common.script"

//--------------------------------------------------------------------------------------------------

Point playerSize = player.GetSize ();
Point screenSize = screen.GetWindowSize ();

//--------------------------------------------------------------------------------------------------

void Start ()
{
    SetSceneAudioStream ("music/Caketown 1.ogg");
}

//--------------------------------------------------------------------------------------------------

void SceneChanged (const string &in previousSceneName)
{
}

//--------------------------------------------------------------------------------------------------

void BeforeEnterScene ()
{
    RegisterFunctions ();    

    SetSuppressSceneInfo (false);
    camera.SetFollowActor (player);

    GetActor ("npc_x").AssignFlagPointsToWalk ("A");
    GetActor ("npc_girl").AssignFlagPointsToWalk ("NPC_1_A");
}

//--------------------------------------------------------------------------------------------------

void AfterLeaveScene ()
{
    SetStepOverlayActive (false);
}

//--------------------------------------------------------------------------------------------------

void PlayerActionHandler ()
{
    player.RegisterActorAction ("my_action", "npc_girl", function (actor)
    {
        //player.TalkTo (actor, "GREET_1").SetHandleFunction (function () 
//        { 
 //           Log ("OK!!!"); 
   //     });
    });
}

//--------------------------------------------------------------------------------------------------

void RegisterFunctions ()
{
    RegisterChoiceFunction ("choice1", function ()
    {
        return "SPCH_2";
    });  
    
    player.SetActionHandler (PlayerActionHandler);  
}

//--------------------------------------------------------------------------------------------------

void Update (float deltaTime)
{
}
