//--------------------------------------------------------------------------------------------------

void ShowSpeechWhenOverlap (Actor@ other, string objectName, string speechID)
{
    if (other.Name == objectName)
    {
        AddSpeechFrame (speechID, false);
    } 
}

//--------------------------------------------------------------------------------------------------

void HideSpeechWhenOverlap (Actor@ other, string objectName, string speechID)
{
    if (other.Name == objectName)
    {
        RemoveSpeechFrame (speechID);
    } 
} 

//--------------------------------------------------------------------------------------------------