void Start ()
{
    SetSceneAudioStream ("music/Little People At Work.ogg");
}

void SceneChanged (const string &in previousSceneName)
{
    camera.SetFollowActor (player);
}

void BeforeEnterScene ()
{
    GetSceneAudioStream ().Play ();
    GetSceneAudioStream ().SetFadeIn (500.f);   
}

void AfterLeaveScene ()
{
    if (GetSceneAudioStream () !is null)
    {
        GetSceneAudioStream ().SetFadeOut (500.f, true);
    }
}

void Update (float deltaTime)
{
}