void Start ()
{
    SetSceneAudioStream ("music/Meadow Thoughts.ogg");
}

void SceneChanged (const string &in previousSceneName)
{
    camera.SetFollowActor (player);
}

void BeforeEnterScene ()
{
    SetSuppressSceneInfo (false);

    GetSceneAudioStream ().Play ();
    GetSceneAudioStream ().SetFadeIn (500.f);    
}

void AfterLeaveScene ()
{
    GetSceneAudioStream ().SetFadeOut (500.f, true);
}

void Update (float deltaTime)
{
}
